[package]
name = "turing-machine-rs"
description = "Turing machine implementation."

readme = "README.md"
license = "MIT"

repository = "https://github.com/TheLazyFerret/turing-machine-rs"

version = "0.0.0"
edition = "2024"

[dependencies]
toml = "0.9.8"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }