"ntapes" = 1
"initial" = 0
"accept" = [0]

[[transition]]
"from" = 0
"next" = 1
"read" = ['a']
"write" = ['M']
"direction" = ["Right"]

[[transition]]
"from" = 1
"next" = 0
"read" = ['a']
"write" = ['M']
"direction" = ["Right"]