"ntapes" = 2
"initial" = 0
"accept" = [0]

[[transition]]
"from" = 0
"next" = 1
"read" = "aβ"
"write" = "Mβ"
"direction" = ["Right", "Right"]

[[transition]]
"from" = 1
"next" = 0
"read" = "aβ"
"write" = "Mβ"
"direction" = ["Right", "Right"]