"ntapes" = 2
"initial" = 0
"accept" = [5]

[[transition]]
"from" = 0
"next" = 1
"read" = "aβ"
"write" = "Xβ"
"direction" = ["Right", "Stop"]

[[transition]]
"from" = 1
"next" = 1
"read" = "bβ"
"write" = "bN"
"direction" = ["Right", "Right"]

[[transition]]
"from" = 1
"next" = 1
"read" = "aβ"
"write" = "aβ"
"direction" = ["Right", "Stop"]

[[transition]]
"from" = 1
"next" = 2
"read" = "cβ"
"write" = "cβ"
"direction" = ["Left", "Stop"]

[[transition]]
"from" = 2
"next" = 2
"read" = "aβ"
"write" = "aβ"
"direction" = ["Left", "Stop"]

[[transition]]
"from" = 2
"next" = 2
"read" = "bβ"
"write" = "bβ"
"direction" = ["Left", "Stop"]

[[transition]]
"from" = 2
"next" = 0
"read" = "Xβ"
"write" = "Xβ"
"direction" = ["Right", "Stop"]

[[transition]]
"from" = 0
"next" = 3
"read" = "bβ"
"write" = "bβ"
"direction" = ["Right", "Stop"]

[[transition]]
"from" = 3
"next" = 3
"read" = "bβ"
"write" = "bβ"
"direction" = ["Right", "Stop"]

[[transition]]
"from" = 3
"next" = 4
"read" = "cβ"
"write" = "cβ"
"direction" = ["Stop", "Left"]

[[transition]]
"from" = 4
"next" = 4
"read" = "cN"
"write" = "cN"
"direction" = ["Right", "Left"]

[[transition]]
"from" = 4
"next" = 5
"read" = "ββ"
"write" = "ββ"
"direction" = ["Stop", "Stop"]